/**
 * AI Analysis Models
 *
 * Defines response structures for AI-powered cryptocurrency analysis
 * Generated by Gemini API for individual coin analysis
 */

/**
 * Individual insight from AI analysis
 * Represents a single observation or finding about the cryptocurrency
 */
export interface Insight {
  /** Insight title/headline */
  title: string;
  /** Detailed description of the insight */
  description: string;
  /** Sentiment classification */
  type: 'positive' | 'negative' | 'neutral';
}

/**
 * Complete AI analysis response for a cryptocurrency
 *
 * Contains AI-generated insights including:
 * - Technical analysis
 * - Fundamental analysis
 * - Sentiment analysis
 * - Market trends
 */
export interface CoinAnalysisResponse {
  /** Cryptocurrency symbol analyzed */
  symbol: string;
  /** Timestamp of analysis generation */
  analyzedAt: string;
  /** Array of AI-generated insights */
  insights: Insight[];
  /** Data source identifier */
  source: string;
  /** Current price at time of analysis */
  currentPrice: number;
  /** 7-day price change percentage */
  percentChange7d: number;
}
