/**
 * Market Overview AI Analysis Models
 *
 * Defines response structures for AI-powered market-wide analysis
 * Generated by Gemini API for overall cryptocurrency market overview
 */

// ==================== Main Response ====================

/**
 * Complete AI-powered market overview analysis
 *
 * Provides comprehensive market intelligence including:
 * - Overall market trend analysis
 * - Key insights and observations
 * - Top performing and declining cryptocurrencies
 * - Aggregated market statistics
 */
export interface MarketOverviewResponse {
  /** Analysis generation timestamp */
  analyzedAt: string;
  /** Overall market sentiment direction */
  overallTrend: 'bullish' | 'bearish' | 'neutral';
  /** AI-generated market insights */
  insights: Insight[];
  /** Best performing cryptocurrencies */
  topGainers: TopMover[];
  /** Worst performing cryptocurrencies */
  topLosers: TopMover[];
  /** Aggregated market-wide statistics */
  statistics: MarketStatistics;
  /** Data source identifier */
  source: string;
}

// ==================== Supporting Types ====================

/**
 * Individual insight about market conditions
 * AI-generated observation about the market
 */
export interface Insight {
  /** Insight title/headline */
  title: string;
  /** Detailed description */
  description: string;
  /** Sentiment classification */
  type: 'positive' | 'negative' | 'neutral';
}

/**
 * Top gaining or losing cryptocurrency
 * Highlights significant market movers
 */
export interface TopMover {
  /** Cryptocurrency symbol */
  symbol: string;
  /** Full cryptocurrency name */
  name: string;
  /** Current price */
  price: number;
  /** 24-hour price change percentage */
  percentChange24h: number;
  /** Market capitalization */
  marketCap: number;
}

/**
 * Comprehensive market-wide statistics
 * Aggregated metrics across all tracked cryptocurrencies
 */
export interface MarketStatistics {
  /** Total cryptocurrency market capitalization */
  totalMarketCap: number;
  /** Total 24-hour trading volume */
  totalVolume24h: number;
  /** Number of cryptocurrencies tracked */
  totalCoins: number;
  /** Bitcoin market dominance percentage */
  btcDominance: number;
  /** Ethereum market dominance percentage */
  ethDominance: number;
  /** Count of cryptocurrencies with positive 24h change */
  coinsUp: number;
  /** Count of cryptocurrencies with negative 24h change */
  coinsDown: number;
  /** Market breadth indicator (coinsUp / (coinsUp + coinsDown)) */
  marketBreadth: number;
  /** Average price change across all coins */
  averageChange24h: number;
  /** Median price change across all coins */
  medianChange24h: number;
  /** Total volume to market cap ratio */
  volumeToMarketCapRatio: number;
  /** Overall market volatility indicator */
  volatilityIndex: number;
}
